### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by monokrome** [AtomLinter/ansible-lint#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-ansible-lint](https://github.com/AtomLinter/ansible-lint) package, v0.0.7

### Stack Trace

Failed to activate the linter package

```
At Cannot find module '/Users/monokrome/.atom/packages/linter-ansible-lint/lib/linter-ansible-lint'

Error: Cannot find module '/Users/monokrome/.atom/packages/linter-ansible-lint/lib/linter-ansible-lint'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at LinterInitializer.activate (/Users/monokrome/.atom/packages/linter/lib/init.coffee:107:30)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:242:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:215:14)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "solarized-dark-ui",
      "solarized-dark-syntax"
    ],
    "followSymlinks": true,
    "projectHome": "/Users/monokrome/Projects/britco/",
    "disabledPackages": [
      "flake8",
      "go-format",
      "tabs",
      "one-tab",
      "ctags-status",
      "travis-ci-status",
      "test-status",
      "status-bar"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-jade, v0.1.0
autocomplete-atom-api, v0.8.0
autocomplete-css, v0.6.0
autocomplete-html, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.13.0
autocomplete-plus-python-jedi, v0.3.2
circle-ci, v0.9.1
editor-stats, v0.17.0
language-ansible, v0.1.3
language-cmake, v0.1.3
language-viml, v0.2.0
linter, v0.12.1
linter-ansible-lint, v0.0.7
linter-coffeelint, v0.2.3
linter-cpplint, v0.1.4
linter-flake8, v1.4.0
linter-jsonlint, v0.1.3
pretty-json, v0.3.3
solarized-dark-ui, v0.3.0
vim-mode, v0.46.0
zentabs, v0.8.4

# Dev
No dev packages
```

**Comment by revolunet** [comment]
same here

**Comment by Arcanemagus** [comment]
This was never implemented, marking as closed.

**Comment by monokrome** [comment]
@Arcanemagus Then why is it in the package repository?

**Comment by steelbrain** [comment]
@monokrome It was removed yesterday :wink:

**Comment by monokrome** [comment]
Thanks! :)
